HODS-388 | Removed sandbox implementation
hmrc/individuals-benefits-and-credits-api pull request #103
Opened 2021-09-07 15:50 UTC by matthewharris1

2021-09-07 16:06 UTC, owen-opencast requested changes

2021-09-07 16:06 UTC, owen-opencast commented on app/uk/gov/hmrc/individualsbenefitsandcreditsapi/controllers/RootController.scala
> +  val environment = Environment.PRODUCTION
This isn't used anymore, can be deleted

2021-09-07 16:06 UTC, owen-opencast commented on app/uk/gov/hmrc/individualsbenefitsandcreditsapi/controllers/WorkingTaxCreditController.scala
> +  val environment = Environment.PRODUCTION
Not used anymore, can be removed

2021-09-07 16:06 UTC, owen-opencast commented on app/uk/gov/hmrc/individualsbenefitsandcreditsapi/controllers/ChildTaxCreditController.scala
> +  val environment = Environment.PRODUCTION
Not used anymore, can be removed

2021-09-07 16:16 UTC, owen-opencast approved these changes

2021-09-08 08:30 UTC, ajchilts approved these changes
Please address @owen-opencast review comments then we can run regression pack and merge. Nice job. 👍

2021-09-08 08:59 UTC, ajchilts approved these changes

2021-09-08 10:21 UTC, merged