MDS207 | Implement authentication model in conjunction with scope handler pattern
hmrc/individuals-benefits-and-credits-api pull request #24
Opened 2020-10-01 15:23 UTC by ajchilts

2020-10-02 09:59 UTC, parkeradam approved these changes
LGTM

2020-10-02 10:03 UTC, parkeradam reviewed
No Api config class?
Ignore pulled locally and seen its there.

2020-10-02 16:16 UTC, owen-opencast requested changes
Just a couple of small changes. Test coverage is down slightly (mostly the exceptions in CommonController that aren't being triggered), think that can be fixed later though.

2020-10-02 16:16 UTC, owen-gilfellon commented on app/uk/gov/hmrc/individualsbenefitsandcreditsapi/domains/ErrorResponses.scala
> +class ScopeAuthorisationException(message: String)
ScopeAuthorisationException and ValidationException not used

2020-10-02 16:16 UTC, owen-gilfellon commented on app/uk/gov/hmrc/individualsbenefitsandcreditsapi/services/ScopesService.scala
> +      .filter(s => s.fields.toSet.subsetOf(keys.toSet))
This doesn't work if a scope has fields from multiple endpoints (e.g. a default scope) - definition of this.subsetOf(that) is "true if this set is a subset of that, i.e. if every element of this set is also an element of that".... suggest something like:
`.filter(s => s.fields.toSet.intersect(keys.toSet).nonEmpty)`

2020-10-05 15:26 UTC, owen-opencast approved these changes

2020-10-06 08:17 UTC, merged