updated config for planned endpoints and scopes.
hmrc/individuals-benefits-and-credits-api pull request #36
Opened 2020-11-13 14:59 UTC by parkeradam

2020-11-16 10:32 UTC, ajchilts commented on conf/application.conf
> +            K = "applications/awards/payments/startDate"
You might be able to explain this better as you have looked into this however; why do we have duplicate paths with different keys in each case? 

I.e. 

K = "applications/awards/payments/startDate"

and

Q = "applications/awards/payments/startDate"

2020-11-16 10:43 UTC, ajchilts requested changes

2020-11-16 10:43 UTC, ajchilts commented on conf/application.conf
> +    benefitsAndCredits {
Also this endpoint config looks different to that in the test config used bu the code for testing the handler pattern. 

```
    endpoints = List(
      EndpointConfig(
        name = mockEndpoint1,
        link = "/a/b/c?matchId=<matchId>{&fromDate,toDate}",
        fields = Map(
          "A" -> "payments",
          "B" -> "employer/employerName=\"foo bar\"",
          "C" -> "employer/employerAddress/line1",
          "D" -> "employer/employerAddress/line2",
          "E" -> "employer/employerAddress/line3",
          "F" -> "employer/employerDistrictNumber",
          "G" -> "employer/employerSchemeReference",
          "H" -> "employmentStartDate",
          "I" -> "employmentLeavingDate",
          "J" -> "employmentPayFrequency",
          "K" -> "employeeAddress",
          "L" -> "payrollId"
        )
      ),
```

I think we will need to align to this name, link, fields 

Name is the string name of the endpoint used by the endpoint to fetch the scopes. 

Link is the full url for HAL 

Fields are the fields. 

@owen-opencast  can help confirm this?

2020-11-16 11:11 UTC, ajchilts requested changes

2020-11-16 11:11 UTC, ajchilts commented on conf/application.conf
> +        endpoint = "individuals/benefits-and-credits"
Update to correct HAL link and ensure endpoint keys match those in the controllers `getEndPointScopes` invocation.

2020-11-16 13:16 UTC, owen-opencast requested changes

2020-11-16 13:16 UTC, owen-opencast commented on conf/application.conf
> +            S = "applications/awards/workingTaxCredit/piadYTD"
Spelling

2020-11-16 13:16 UTC, owen-opencast commented on conf/application.conf
>      hello {
Remove placeholder config?

2020-11-16 15:14 UTC, ajchilts requested changes

2020-11-16 15:14 UTC, ajchilts commented on conf/application.conf
> +        endpoint = "/individuals/benefits-and-credits/child-tax-credit?matchId=$randomMatchId"
I believe this link should have a startDate and endDate range.

2020-11-16 15:14 UTC, ajchilts commented on conf/application.conf
> +        endpoint = "/individuals/benefits-and-credits/working-tax-credit?matchId=$randomMatchId"
I believe this link should have a startDate and endDate range.

2020-11-16 15:14 UTC, ajchilts commented on conf/application.conf
> +        endpoint = "individuals/benefits-and-credits?matchId=$randomMatchId"
I believe this link should have a startDate and endDate range.

2020-11-18 14:34 UTC, ajchilts approved these changes

2020-11-18 14:34 UTC, merged

2020-11-18 14:34 UTC, owen-opencast commented on test/component/uk/gov/hmrc/individualsbenefitsandcreditsapi/controllers/LiveChildTaxCreditControllerSpec.scala
> +      println(response.body)
Remove println

2020-11-18 14:35 UTC, owen-opencast commented on conf/application.conf
> +      child-tax-credit {
benefitsAndCredits is camel case, but hyphens here?